apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labes:
    type: local
spec:
  storageClassname: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
